---
title: "Approaches"
author: "Alexander Aksentyev"
date: "October 25, 2016"
output: html_document
---

## Outline

The less information is required to reach a conclusion, the more precise and accurate it is. Hence, there can be two strategies to deal with systematics:

 * More detailed specification of the used model, which leads to increased accuracy at the expense of precision, or
 * Reduction of the problem to a less information-demanding state. (Choice of a better estimator falls under this category.)
 
Procedurally, the first strategy requires improved specification of the statistical information about the process analyzed to then extract substantive information from the data. [Aris Spanos](http://faculty.chicagobooth.edu/midwest.econometrics/papers/megspanos.pdf)

The second approach consists in representing the problem in terms of its information/[uncertainty content](https://www.irit.fr/~Didier.Dubois/Papers1208/IncertitudeEnglish.pdf) and then **transforming** it to an equivalent, but less complex, problem; possible worlds semantic/epistemic logic.

## Reductionist approach

Systematic errors are the features of an experiment's operation that the experimenter is unaware of. Thus it follows that to effectively fight the problem of systematic errors, one must choose a way of arriving at the conclusion (probabilistic statement regarding the sought after value) that requires the least amount of information (both qualitative --- number of parameters, --- and quantitative --- the amount of data required to estimate those parameters with necessary precision). To do that, one must order all possible ways of proceeding according to their information requirement. To do *that* one needs to

1. formulate the notion (mathematical structure) of *way of arrival at a conclusion*;
2. for the conclusion whose value is being sought, subset the domain of its ways of arrival from those of arriving at *other* conclusions (ex-/inclusively);
3. express them in terms of their information requirements (presumably, as **sets** with added structure) and order them (by **cardinality**?)

### Example of ratio and difference statistics

Given the data set we have (current and time; derivative: slope), there are two *known* ways to form the statistic for the determination of the value of Ayy: the difference statistic, and the ratio statistic. 

The difference statistic leads to a family of probability distributions labeled by **two** independent (**nuisance**) parameters: cross section and target thickness. The statistic estimating cross section requires knowledge of target thickness and an extra set of experiments; the estimation of target thickness requires extra data. 

$$
  \hat{A}_{y,y}^D(\sigma_0\Theta_{on}) = \frac12\frac{(\hat{\beta}_{on}^--\hat{\beta}_{on}^+)(A_{y,y})}{P^tP\cdot\nu}\cdot\frac1{\sigma_0\Theta_{on}},~ \hat{\sigma}_0 = \hat{\sigma}_0(\Theta_{on}).
$$

To the primary $\pm$-on experiment, an auxiliarry 0-on/0-valve experiment is required, as well as an estimate of $\Theta_{on}$, to estimate cross section.

On the other hand, the ratio statistic involves, as a nuisance parameter, the ratio of extra-target loss to that within the target, which is **presumably** easier for estimation than cross section and target thickness.

$$
  \hat{A}_{y,y}^R = \frac{\hat{R}(A_{y,y}; x)}{P^tP}(1+x), ~ x = \frac{\sigma_x\Theta_x}{\sigma_0\Theta_{on}},
$$
$$
  \hat{R}(A_{y,y}; x) = \frac{\hat{\beta}_{on}^-/\hat{\beta}_{on}^+ - 1}{\hat{\beta}_{on}^-/\hat{\beta}_{on}^+ + 1},
$$
$$
  \hat{x} = -\frac12(\frac{1}{\hat{R}'} + 1), ~\hat{R}' = \frac{\hat{\beta}_{valve}^0/\hat{\beta}_{on}^0-1}{\hat{\beta}_{valve}^0/\hat{\beta}_{on}^0+1}
$$

This estimator only requires an auxilliary 0-on/0-valve experiment.

### Glossary

**[Term.](http://www.0up.ir/do.php?downexf=n41main.pdf)** a term $t$ is a variable $t=v_i$, or constant $t=c_j$ symbol, or a function $t=ft_1\dots t_n$ thereof.

**Formula.** A formula is either $Rt_1\dots t_m$, or a combination thereof.

**Interpretation.** A function from a language to a mathematical structure, mapping each relation/function/constant symbol of the language to a relation/function/constant of the structure.

**Semantics.** The codomain ($f:X\mapsto Y$; X is domain, Y is codomain) of an interpretation.

**Possible Worlds Semantics.** A mathematical structure with two relations (called necessity and possibility), whose elements are called possible worlds, and which is used to define the notions _necessary_ and _possible_.

**Truenness.** A statement is true, if there exists an interpretation making it true. A statement is tautological, if it is true in all structures.

**Logic.** The study of going from a true (in a structure) statement to a true statement.

**[Epistemic logic.](plato.stanford.edu/entries/logic-epistemic/)** Same as logic when the formal language involves the notions _known_ and _believed_. Ex. if A _knows_ that $\phi$ is true ($K_A\phi$), then in all possible worlds compatible with what A knows, $\phi$ is assigned the value 'true.'